openapi: 3.0.0
info:
    version: 1.0.0
    title: JSON Placeholder API
    description: See https://jsonplaceholder.typicode.com/
paths:
    /projects:
      post:
        description: Create a new project
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  shortName:
                    type: string
        responses:
          '200':
            description: Success
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: number
                      const: 200
          '400':
            description: Bad Request
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: number
                      const: 400
    /login:
            post:
                description: Login with user credentials
                tags: ['Authentication']
                operationId: 'loginUser'
                requestBody:
                    required: true
                    content:
                        'application/x-www-form-urlencoded':
                            schema:
                                type: object
                                properties:
                                    login:
                                        type: string
                responses:
                    '200':
                        description: Successful login
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        status:
                                            type: integer
                                            example: 200
                    '400':
                        description: Invalid login credentials
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        status:
                                            type: integer
                                            example: 400
    /posts:
        get:
            description: Returns all posts
            tags: ['Posts']
            operationId: 'getPosts'
            responses:
                '200':
                    description: Successful response
                    content:
                        'application/json':
                            schema:
                                $ref: '#/components/schemas/PostsList'

    /posts/{id}:
        get:
            description: Returns a post by id
            tags: ['Posts']
            operationId: 'getPost'
            parameters:
                - name: id
                  in: path
                  required: true
                  description: The user id.
                  schema:
                      type: integer
                      format: int64
            responses:
                '200':
                    description: Successful response
                    content:
                        'application/json':
                            schema:
                                $ref: '#/components/schemas/Post'
                '404':
                    description: Post not found

components:
    schemas:
        PostsList:
            'type': 'array'
            'items':
                $ref: '#/components/schemas/Post'
        Post:
            'type': 'object'
            'required':
                - 'id'
                - 'userId'
                - 'title'
                - 'completed'
            'properties':
                id:
                    type: 'integer'
                userId:
                    type: 'integer'
                title:
                    type: 'string'
                body:
                    type: 'string'
